name: just_example on needs
on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.generate_id.outputs.id }}
    steps:
      - name: Generate a unique build ID
        id: generate_id
        run: echo "id=build-$(date +%s)" >> $GITHUB_OUTPUT
      - name: Run build process...
        run: |
          echo "Build ID: ${{ steps.generate_id.outputs.id }}"
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    env:
      x: "${{ needs.build.outputs.build_id }}"
    needs: build
    steps:
      - name: get repo 
        uses: actions/checkout@v3
      - name: Deploying with the correct ID
        run: echo "Deploying Build ID:${x}"
      - name: echo note
        run: echo "::debug::The value of variable x is something debug"
      - name: echo notice
        run: echo "::notice::The value of variable x is something note"
      - name: echo warning
        run: echo "::warning::The value of variable x is something warning"
      - name: echo error
        run: echo "::error::This is an error message error"
      - name: Check build result (just for demonstration)
        if: ${{ needs.build.result == 'success' }}
        run: echo "The build job was successful!"
      - name: just echo id
        run: echo ${{needs.build.outputs.build_id}}
  just_another_Deploy:
    name: just anthor Deploy to Production
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download the repository code
        uses: actions/checkout@v3

      - name: Deploy with Build ID
        env:
          BUILD_ID: ${{ needs.build.outputs.build_id }}
        run: echo "Starting deployment for Build ID -> $BUILD_ID"

      - name: Demonstrate Different Workflow Commands
        run: |
          echo "::debug::This is a general debug message."
          echo "::notice::This is a general notice message."
          echo "::warning::This is a general warning message."
          echo "::error::This is a general error message."

          echo "----------------------------------------------------"
          echo "::notice file=README.md,line=1,title=FYI,endColumn=7::Just a note on the README file."
          echo "::warning file=README.md,line=2,title=Potential Issue,endColumn=3::This line might need a review."
          echo "::error file=README.md,line=4,title=Critical Error,endColumn=5::Something is wrong on this line!"

      - name: Check build job result
        if: ${{ needs.build.result == 'success' }}
        run: echo "Great! The 'build' job was successful, so we are deploying."
